services:
  mysql:
    container_name: mysqlserver
    hostname: mysql
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=db_example
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_ROOT_PASSWORD=ThePassword
    restart: on-failure:2
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  api:
    container_name: api  
    restart: on-failure:2
    hostname: api
    depends_on:
      - mysql
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    networks:
      - backend
    expose:
      - '9000'

  webangular:
    container_name: angularserver
    restart: on-failure:2
    hostname: webangular
    depends_on:
      - mysql
      - api
    build:
      context: ./webangular
      dockerfile: Dockerfile
    volumes:
      - ./webangular:/app
    networks:
      - frontend

  # mqtt5 eclipse-mosquitto
  mqtt5:
    image: iegomez/mosquitto-go-auth
    container_name: mqtt5
    restart: on-failure:2
    hostname: mqtt5
    depends_on:
      - api
      - redis
    networks:
      - backend
      - frontend
    ports:
      - "8083:8083" #default mqtt port for websockets
    volumes:
      - ./mosquitto/conf:/etc/mosquitto/:rw

  redis:
    image: redis:6.2-alpine
    container_name: redis
    hostname: redis
    restart: on-failure:2
    networks:
      - backend
    expose:
      - '6379'  
    command: redis-server /data/redis.conf --loglevel warning
    volumes: 
      - ./redis:/data

  proxy:
    image: nginx:latest
    container_name: proxy
    hostname: proxy
    restart: on-failure:2
    networks:
      - backend
      - frontend
    volumes: 
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/proxy_params:/etc/nginx/proxy_params
      - ./proxy/ssl:/etc/ssl
    ports:
      - 80:80
      - 443:443

volumes:
  mysql-data:

networks:
  backend:
  frontend:
