services:
  mysql:
    container_name: mysqlserver  
    hostname: mysql
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=db_example
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_ROOT_PASSWORD=ThePassword
    restart: on-failure:2
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  api:
    container_name: apiserver  
    restart: on-failure:2
    hostname: api
    depends_on:
      - mysql
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    networks:
      - frontend
      - backend
    ports:
      - 9000:9000

  webangular:
    container_name: angularserver
    restart: on-failure:2
    hostname: web-angular
    depends_on:
      - mysql
      - api  
    build:
      context: ./webangular
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./webangular:/app
    networks:
      - frontend
    ports:
      - 4200:4200

  # mqtt5 eclipse-mosquitto
  mqtt5:
    image: iegomez/mosquitto-go-auth
    container_name: mqtt5
    restart: on-failure:2
    hostname: mqtt5
    depends_on:
      - api
      - redis
    networks:
      - frontend
    ports:
      - "8083:8083" #default mqtt port for websockets
    volumes:
      - ./mosquitto/conf:/etc/mosquitto/:rw

  redis:
    image: redis:6.2-alpine
    container_name: redis
    hostname: redis
    restart: on-failure:2
    networks:
      - frontend
    expose:
      - '6379'
    command: redis-server /data/redis.conf --loglevel warning
    volumes: 
      - ./redis:/data


volumes:
  mysql-data:
  cache:

networks:
  backend:
  frontend:
